import { useEffect, useMemo, useState } from 'react';
import type { ChangeEvent } from 'react';
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Anchor, Bookmark, Check, ChevronRight, CircleUserRound, Clock3, Compass, FileUp, LogOut, Menu, Search, ShieldCheck, Waves, X } from 'lucide-react';
import { deriveAnalysis } from '../analysis';
import { DiveParseError, friendlyName, parseDive, type Dive } from '../parser';
import { supabase } from '../supabase';

const fixtureFiles = Object.keys(import.meta.glob('/public/sample-dives/*.ssrf')).map(p=>p.split('/').at(-1)!).sort();
const publicPath=(name:string)=>`/sample-dives/${name}`;
type Saved={id:string;title:string;notes:string;summary:Record<string,unknown>;source_xml:string;source_filename:string;created_at:string};
const fmt=(v:number|undefined,digits=1)=>v===undefined?'—':v.toFixed(digits);
const timeLabel=(m:number)=>`${Math.floor(m)}:${String(Math.round((m%1)*60)).padStart(2,'0')}`;

export default function App(){
 const [dive,setDive]=useState<Dive|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[user,setUser]=useState<any>(null),[saved,setSaved]=useState<Saved[]>([]),[view,setView]=useState<'analyze'|'dives'>('analyze');
 const [authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState<'signin'|'signup'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authError,setAuthError]=useState('');
 const [edit,setEdit]=useState<Saved|null>(null),[query,setQuery]=useState('');
 const analysis=useMemo(()=>dive?deriveAnalysis(dive):null,[dive]);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(user)refreshSaved()},[user]);
 async function refreshSaved(){if(!supabase)return;try{const {data,error:e}=await supabase.from('saved_dives').select('*').order('created_at',{ascending:false});if(e)throw e;setSaved((data??[]) as Saved[])}catch(e){setError(`Could not load saved dives: ${e instanceof Error?e.message:'Network request failed.'}`)}}
 function parse(xml:string,name:string){try{const result=parseDive(xml,name);setDive(result);setView('analyze');setError('');window.scrollTo({top:0,behavior:'smooth'})}catch(e){setDive(null);setError(e instanceof DiveParseError?e.message:'Could not read this dive file.');}}
 async function chooseSample(name:string){setBusy(true);setError('');try{const res=await fetch(publicPath(name));if(!res.ok)throw new Error('Sample file could not be loaded.');parse(await res.text(),name)}catch(e){setError(e instanceof Error?e.message:'Sample dive unavailable.')}finally{setBusy(false)}}
 async function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setBusy(true);setError('');try{parse(await f.text(),f.name)}finally{setBusy(false);e.target.value=''}}
 async function authSubmit(e:React.FormEvent){e.preventDefault();if(!supabase){setAuthError('Supabase is not configured. Add the environment variables and reload.');return}setAuthError('');try{const result=authMode==='signup'?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(result.error)setAuthError(result.error.message);else if(authMode==='signup'&&!result.data.session)setAuthError('Check your email to confirm your account, then sign in.');else setAuthOpen(false)}catch(e){setAuthError(e instanceof Error?e.message:'Authentication request failed.')}}
 async function saveDive(){if(!dive||!supabase||!user)return;try{const {error:e}=await supabase.from('saved_dives').insert({user_id:user.id,title:dive.site?`${dive.site} · ${dive.date??'Dive'}`:`Dive ${dive.number??''}`.trim(),notes:'',source_filename:dive.filename,source_xml:dive.rawXml,summary:{date:dive.date,site:dive.site,maxDepthM:dive.maxDepthM,durationMinutes:dive.durationMinutes}});if(e)throw e;setError('');await refreshSaved();setView('dives')}catch(e){setError(`Save failed: ${e instanceof Error?e.message:'Network request failed.'}`)}}
 async function updateSaved(){if(!edit||!supabase)return;try{const {error:e}=await supabase.from('saved_dives').update({title:edit.title,notes:edit.notes}).eq('id',edit.id);if(e)throw e;setEdit(null);await refreshSaved()}catch(e){setError(`Update failed: ${e instanceof Error?e.message:'Network request failed.'}`)}}
 async function deleteSaved(id:string){if(!supabase)return;try{const {error:e}=await supabase.from('saved_dives').delete().eq('id',id);if(e)throw e;await refreshSaved()}catch(e){setError(`Delete failed: ${e instanceof Error?e.message:'Network request failed.'}`)}}
 async function signOut(){try{const {error:e}=await supabase?.auth.signOut()??{};if(e)throw e;setSaved([])}catch(e){setError(`Sign out failed: ${e instanceof Error?e.message:'Request failed.'}`)}}
 const shownSaved=saved.filter(s=>`${s.title} ${s.source_filename}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="app-shell">
  <header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView('analyze')}}><span className="brand-mark"><Waves size={20}/></span><span>DIVE<span className="brand-light">ANALYZER</span></span></a><nav><button className={view==='analyze'?'nav-active':''} onClick={()=>setView('analyze')}>Analyze</button>{user&&<button className={view==='dives'?'nav-active':''} onClick={()=>setView('dives')}>My dives <span className="nav-count">{saved.length}</span></button>}</nav><div className="top-actions">{user?<><span className="user-email"><CircleUserRound size={16}/>{user.email}</span><button className="icon-button" title="Sign out" onClick={signOut}><LogOut size={17}/></button></>:<button className="signin" onClick={()=>{setAuthMode('signin');setAuthOpen(true)}}>Sign in <ChevronRight size={15}/></button>}<button className="mobile-menu"><Menu size={19}/></button></div></header>
  <main>
   {view==='analyze'?<>
    {!dive&&<section className="hero"><div className="hero-content"><div className="eyebrow"><span className="live-dot"/> DIVE LOG ANALYSIS, MADE CLEAR</div><h1>Read the water.<br/><em>Know every moment.</em></h1><p>Turn a Subsurface dive log into a clear picture of your time underwater.</p><label className="upload-button"><FileUp size={17}/>{busy?'Reading dive…':'Upload a dive log'}<input type="file" accept=".ssrf,.xml,text/xml,application/xml" onChange={upload} disabled={busy}/></label><span className="upload-hint">Single dive · Subsurface .ssrf or .xml</span><div className="hero-stats"><span><ShieldCheck size={15}/> Private in your browser</span><span><Anchor size={15}/> No account needed</span></div></div><div className="hero-art"><div className="sun"/><div className="waterline"/><div className="depth-line depth-a"/><div className="depth-line depth-b"/><div className="depth-line depth-c"/><div className="contour contour-a"/><div className="contour contour-b"/><div className="hero-tag tag-top"><span>MAX DEPTH</span><b>28.4 <small>m</small></b></div><div className="hero-tag tag-bottom"><span>TIME BELOW</span><b>44:10 <small>min</small></b></div><div className="dive-figure"><div className="diver-head"/><div className="diver-body"/><div className="diver-fin"/></div><div className="bubbles">·　·<br/>　·</div><div className="depth-scale"><span>0m</span><span>10m</span><span>20m</span><span>30m</span></div></div></section>}
    {!dive&&<section className="sample-section"><div className="section-heading"><div><span className="eyebrow muted">START WITH A REAL DIVE</span><h2>Explore a sample log</h2></div><span className="sample-count">10 REAL DIVE LOGS</span></div><div className="sample-grid">{fixtureFiles.map((f,i)=><button className="sample-card" key={f} onClick={()=>chooseSample(f)} disabled={busy}><span className={`sample-index index-${i%4}`}>{String(i+1).padStart(2,'0')}</span><span className="sample-info"><b>{friendlyName(f)}</b><small>{f.includes('teric')||f.includes('Teric')?'Shearwater Teric':f.includes('manual')?'Manual profile':'DL7 computer'}</small></span><ChevronRight size={17}/></button>)}</div><p className="sample-foot">Every sample is parsed from its original Subsurface file. Missing measurements stay unavailable.</p></section>}
    {dive&&analysis&&<AnalysisView dive={dive} onSave={user?saveDive:()=>{setAuthMode('signup');setAuthOpen(true)}} isSaved={!!user}/>}
   </>:<section className="saved-page"><div className="saved-head"><div><span className="eyebrow muted">YOUR PERSONAL LOGBOOK</span><h1>My dives<span className="period">.</span></h1><p>Your saved dives, ready when you are.</p></div><div className="saved-user"><CircleUserRound size={18}/>{user?.email}</div></div><div className="search-box"><Search size={17}/><input placeholder="Search your dives" value={query} onChange={e=>setQuery(e.target.value)}/><span>{shownSaved.length} dives</span></div>{shownSaved.length?<div className="saved-list">{shownSaved.map(s=><SavedRow key={s.id} item={s} onOpen={()=>parse(s.source_xml,s.source_filename)} onEdit={()=>setEdit(s)} onDelete={()=>deleteSaved(s.id)}/>)}</div>:<div className="empty-state"><div className="empty-icon"><Bookmark/></div><h3>{saved.length?'No matching dives':'Your logbook is waiting'}</h3><p>{saved.length?'Try a different search.':'Analyze a dive and save it here to build your personal logbook.'}</p><button className="outline-button" onClick={()=>setView('analyze')}>Analyze a dive <ChevronRight size={15}/></button></div>}</section>}
   {error&&<div className="error-banner"><X size={17}/><span>{error}</span><button onClick={()=>setError('')}><X size={16}/></button></div>}
  </main>
  <footer><a className="brand footer-brand" href="#" onClick={e=>{e.preventDefault();setView('analyze')}}><span className="brand-mark"><Waves size={17}/></span><span>DIVE<span className="brand-light">ANALYZER</span></span></a><span>Built for curious divers. <span className="footer-sep">·</span> Your data stays yours.</span><span className="footer-right">SUBSURFACE LOG ANALYSIS</span></footer>
  {authOpen&&<div className="modal-backdrop" onClick={()=>setAuthOpen(false)}><div className="auth-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAuthOpen(false)}><X size={18}/></button><span className="brand-mark modal-mark"><Waves/></span><h2>{authMode==='signin'?'Welcome back':'Save your dive'}</h2><p>{authMode==='signin'?'Sign in to open your dive logbook.':'Create an account to keep this dive in your logbook.'}</p><form onSubmit={authSubmit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label>{authError&&<div className="auth-error">{authError}</div>}<button className="primary-button" type="submit">{authMode==='signin'?'Sign in':'Create account'} <ChevronRight size={16}/></button></form><div className="auth-switch">{authMode==='signin'?"New to Dive Analyzer?":"Already have an account?"} <button onClick={()=>{setAuthError('');setAuthMode(authMode==='signin'?'signup':'signin')}}>{authMode==='signin'?'Create an account':'Sign in'}</button></div><div className="auth-private"><ShieldCheck size={14}/> Dive analysis always works without signing in.</div></div></div>}
  {edit&&<div className="modal-backdrop" onClick={()=>setEdit(null)}><div className="auth-modal edit-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setEdit(null)}><X size={18}/></button><h2>Edit saved dive</h2><label>Title<input value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>Notes<textarea value={edit.notes??''} onChange={e=>setEdit({...edit,notes:e.target.value})} rows={5}/></label><button className="primary-button" onClick={updateSaved}>Save changes <Check size={16}/></button></div></div>}
 </div>
}

function AnalysisView({dive,onSave,isSaved}:{dive:Dive;onSave:()=>void;isSaved:boolean}){
 const a=deriveAnalysis(dive), rows=dive.samples.map(s=>({minute:s.time,depth:s.depth===null?null:Number(s.depth.toFixed(2)),pressure:s.pressure===null?null:Number(s.pressure.toFixed(1)),ndl:s.ndl===null?null:Number(s.ndl.toFixed(0)),temperature:s.temperature===null?null:Number(s.temperature.toFixed(1))}));
 const anyPressure=rows.some(s=>s.pressure!==null), anyNdl=rows.some(s=>s.ndl!==null), anyTemp=rows.some(s=>s.temperature!==null);
 return <section className="analysis"><div className="analysis-top"><button className="back-link" onClick={()=>window.location.reload()}><ChevronRight className="back-arrow" size={15}/> All dives</button><div className="analysis-actions"><span className="source-pill"><span className="live-dot"/> {dive.device??'Subsurface log'}</span><button className="save-button" onClick={onSave}><Bookmark size={16}/>{isSaved?'Save to my dives':'Save this dive'}</button></div></div><div className="analysis-title"><div><span className="eyebrow muted">DIVE {dive.number??'PROFILE'} <span className="eyebrow-dot">·</span> {dive.date??'DATE UNAVAILABLE'}</span><h1>{dive.site??friendlyName(dive.filename)}<span className="period">.</span></h1><p>{dive.date&&dive.time?`${dive.date} · ${dive.time}`:dive.filename} {dive.gps&&<span className="gps"> · {dive.gps}</span>}</p></div><div className="duration-card"><Clock3 size={17}/><div><small>DURATION</small><b>{dive.durationMinutes!==undefined?timeLabel(dive.durationMinutes):'—'} <i>min</i></b></div></div></div>
  <div className="metric-grid"><Metric label="MAX DEPTH" value={fmt(dive.maxDepthM??a.observedMaxDepth)} unit="m" icon="depth"/><Metric label="AVG DEPTH" value={fmt(dive.averageDepthM)} unit="m" icon="avg"/><Metric label="WATER TEMP" value={dive.minTemperatureC===undefined?'—':`${fmt(dive.minTemperatureC)}–${fmt(dive.maxTemperatureC)}°`} unit={dive.minTemperatureC===undefined?'':'C'} icon="temp"/><Metric label="GAS MIX" value={dive.gasMix??'—'} unit={dive.cylinder?.description??''} icon="gas"/></div>
  <div className="chart-card main-chart"><div className="chart-head"><div><span className="eyebrow muted">PROFILE</span><h3>Depth over time</h3></div><span className="chart-unit">DEPTH <b>METRES</b></span></div><div className="chart-area depth-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={rows} margin={{top:12,right:16,left:0,bottom:0}}><defs><linearGradient id="depthFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#39b9ad" stopOpacity={.34}/><stop offset="100%" stopColor="#39b9ad" stopOpacity={.02}/></linearGradient></defs><CartesianGrid stroke="#e9efee" vertical={false}/><XAxis dataKey="minute" tickFormatter={timeLabel} tickLine={false} axisLine={false} minTickGap={60} tick={{fill:'#829096',fontSize:11}}/><YAxis reversed domain={[0,'dataMax + 3']} tickLine={false} axisLine={false} width={42} tick={{fill:'#829096',fontSize:11}}/><Tooltip labelFormatter={v=>`${timeLabel(Number(v))} elapsed`} formatter={(v,n)=>[`${v} ${n==='Depth'?'m':''}`,n]}/><Area type="monotone" dataKey="depth" name="Depth" stroke="#209c92" strokeWidth={2.5} fill="url(#depthFill)" connectNulls={false} activeDot={{r:4,fill:'#209c92'}}/></AreaChart></ResponsiveContainer></div><div className="chart-axis-label">ELAPSED TIME</div></div>
  {(anyPressure||anyNdl||anyTemp)&&<div className="secondary-charts">{anyPressure&&<ChartPanel title="Tank pressure" unit="BAR" data={rows} keyName="pressure" color="#537db4" timeLabel={timeLabel}/ >}{anyNdl&&<ChartPanel title="No decompression limit" unit="MINUTES" data={rows} keyName="ndl" color="#d2a24d" timeLabel={timeLabel}/ >}{anyTemp&&<ChartPanel title="Water temperature" unit="°C" data={rows} keyName="temperature" color="#eb8066" timeLabel={timeLabel}/ >}</div>}
  <div className="details-layout"><div className="detail-card"><div className="detail-heading"><span className="detail-icon"><Compass size={17}/></span><div><span className="eyebrow muted">DIVE DETAILS</span><h3>At a glance</h3></div></div><div className="detail-list"><Detail label="Date & time" value={dive.date?`${dive.date}${dive.time?` · ${dive.time}`:''}`:undefined}/><Detail label="Dive site" value={dive.site}/><Detail label="Computer" value={dive.device}/><Detail label="Duration" value={dive.durationMinutes!==undefined?`${timeLabel(dive.durationMinutes)} min`:undefined}/><Detail label="Maximum ascent rate" value={a.maxAscent!==undefined?`${fmt(a.maxAscent)} m/min`:undefined}/><Detail label="Maximum descent rate" value={a.maxDescent!==undefined?`${fmt(a.maxDescent)} m/min`:undefined}/><Detail label="Minimum NDL" value={a.minNdl!==undefined?`${Math.round(a.minNdl)} min`:undefined}/><Detail label="Average NDL" value={a.averageNdl!==undefined?`${Math.round(a.averageNdl)} min`:undefined}/></div></div><div className="detail-card"><div className="detail-heading"><span className="detail-icon gas-icon"><Anchor size={17}/></span><div><span className="eyebrow muted">GAS & DEPTH</span><h3>Equipment & profile</h3></div></div><div className="detail-list"><Detail label="Gas mix" value={dive.gasMix}/><Detail label="Cylinder" value={dive.cylinder?.description}/><Detail label="Cylinder size" value={dive.cylinder?.sizeL!==undefined?`${fmt(dive.cylinder.sizeL)} L`:undefined}/><Detail label="Starting pressure" value={a.startingPressure!==undefined?`${fmt(a.startingPressure)} bar`:undefined}/><Detail label="Ending pressure" value={a.endingPressure!==undefined?`${fmt(a.endingPressure)} bar`:undefined}/><Detail label="Gas used" value={a.gasUsed!==undefined?`${fmt(a.gasUsed)} bar`:undefined}/><Detail label="Pressure change rate" value={a.pressureRate!==undefined?`${fmt(a.pressureRate)} bar/min`:undefined}/><Detail label="SAC (source reported)" value={dive.sacLMin!==undefined?`${fmt(dive.sacLMin)} L/min`:undefined}/></div></div></div>
  {!!a.bands.length&&<div className="bands-card"><div><span className="eyebrow muted">TIME AT DEPTH</span><h3>Depth bands</h3></div><div className="band-bars">{a.bands.map(b=><div className="band" key={b.label}><div className="band-label"><span>{b.label}</span><b>{fmt(b.minutes)} <small>min</small></b></div><div className="band-track"><span style={{width:`${Math.max(5,b.minutes/(dive.durationMinutes??Math.max(...a.bands.map(x=>x.minutes)))*100)}%`}}/></div></div>)}</div></div>}
  <p className="analysis-note">Metrics are calculated from available profile samples. Blank values mean the source log did not include that measurement.</p>
 </section>
}
function Metric({label,value,unit,icon}:{label:string;value:string;unit:string;icon:string}){return <div className="metric-card"><div className={`metric-icon metric-${icon}`}>{icon==='depth'?<Waves size={17}/>:icon==='avg'?<Compass size={17}/>:icon==='temp'?<span>°</span>:<Anchor size={17}/>}</div><span>{label}</span><b>{value}<small>{unit}</small></b></div>}
function Detail({label,value}:{label:string;value?:string}){return <div className="detail-row"><span>{label}</span><b className={value?'':'unavailable'}>{value??'Unavailable'}</b></div>}
function ChartPanel({title,unit,data,keyName,color,timeLabel}:{title:string;unit:string;data:any[];keyName:string;color:string;timeLabel:(n:number)=>string}){return <div className="chart-card mini-chart"><div className="chart-head"><div><span className="eyebrow muted">PROFILE DATA</span><h3>{title}</h3></div><span className="chart-unit">{unit}</span></div><div className="mini-chart-area"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:10,right:8,left:-18,bottom:0}}><CartesianGrid stroke="#e9efee" vertical={false}/><XAxis dataKey="minute" tickFormatter={timeLabel} tickLine={false} axisLine={false} minTickGap={60} tick={{fill:'#829096',fontSize:10}}/><YAxis tickLine={false} axisLine={false} width={40} tick={{fill:'#829096',fontSize:10}}/><Tooltip labelFormatter={v=>`${timeLabel(Number(v))} elapsed`}/><Line type="monotone" dataKey={keyName} name={title} stroke={color} strokeWidth={2} dot={false} connectNulls activeDot={{r:4}}/></LineChart></ResponsiveContainer></div></div>}
function SavedRow({item,onOpen,onEdit,onDelete}:{item:Saved;onOpen:()=>void;onEdit:()=>void;onDelete:()=>void}){const s=item.summary??{};return <div className="saved-row"><button className="saved-row-main" onClick={onOpen}><span className="saved-row-mark"><Waves size={19}/></span><span className="saved-row-copy"><b>{item.title}</b><small>{String(s.site??'Site unavailable')} <span>·</span> {String(s.date??'Date unavailable')}</small></span><span className="saved-row-metric"><small>MAX DEPTH</small><b>{typeof s.maxDepthM==='number'?`${s.maxDepthM.toFixed(1)} m`:'—'}</b></span><ChevronRight size={18}/></button><div className="saved-row-actions"><button onClick={onEdit}>Edit</button><button onClick={onDelete}>Delete</button></div></div>}
